// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdGm3B2QC8MUAPQCGuL6m8hL3JBLxZRVQ',
    appId: '1:432217464184:web:ba7c3989c8542ce388bc8d',
    messagingSenderId: '432217464184',
    projectId: 'heart-health-app-7d200',
    authDomain: 'heart-health-app-7d200.firebaseapp.com',
    storageBucket: 'heart-health-app-7d200.firebasestorage.app',
    measurementId: 'G-42EK21RHEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJOtRmiAgL3Wl8U5GN1uczM56a2aG3kes',
    appId: '1:432217464184:android:66f51d047de3a44e88bc8d',
    messagingSenderId: '432217464184',
    projectId: 'heart-health-app-7d200',
    storageBucket: 'heart-health-app-7d200.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4uSwyHa1PWMYGAlQgSZosd33PNkyBqJc',
    appId: '1:432217464184:ios:268b25413001e40c88bc8d',
    messagingSenderId: '432217464184',
    projectId: 'heart-health-app-7d200',
    storageBucket: 'heart-health-app-7d200.firebasestorage.app',
    iosBundleId: 'com.example.healthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4uSwyHa1PWMYGAlQgSZosd33PNkyBqJc',
    appId: '1:432217464184:ios:268b25413001e40c88bc8d',
    messagingSenderId: '432217464184',
    projectId: 'heart-health-app-7d200',
    storageBucket: 'heart-health-app-7d200.firebasestorage.app',
    iosBundleId: 'com.example.healthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdGm3B2QC8MUAPQCGuL6m8hL3JBLxZRVQ',
    appId: '1:432217464184:web:1957486ec812956688bc8d',
    messagingSenderId: '432217464184',
    projectId: 'heart-health-app-7d200',
    authDomain: 'heart-health-app-7d200.firebaseapp.com',
    storageBucket: 'heart-health-app-7d200.firebasestorage.app',
    measurementId: 'G-NDM8DL2DL2',
  );
}
